# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-19 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetails',
            old_name='first_name',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='accountdetails',
            old_name='last_name',
            new_name='password',
        ),
    ]
