# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-19 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20171219_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetails',
            old_name='email',
            new_name='mail',
        ),
    ]
