# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-19 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20171219_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountDetails',
        ),
    ]
