# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-20 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_forumpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='contents',
            field=models.TextField(),
        ),
    ]
