# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-21 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20171220_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomSubPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hyperlink', models.CharField(max_length=400)),
                ('subpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Passtime')),
            ],
        ),
    ]
