# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-21 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_randomsubpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passtime',
            name='link',
        ),
    ]
