# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-21 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_passtime_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='JelitoButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=400)),
            ],
        ),
    ]
